### ISSUE TITLE
check(mate)

### ISSUE THREAD

**Issue by mosmar99** [mosmar99/ChessProjectClass#12]
- [ ] Check is a situation in the game of Chess where a player's King is threatened directly by another player's piece. If at any point in the game a player's King is threatened directly by another player's piece so that in their next turn, they will be able to capture him - the other player has put the King in “Check”.
- [ ] A checkmate (also known as "mate") occurs when a king is placed in check and has no legal moves to escape. When a checkmate happens, the game ends immediately, and the player who delivered the checkmate wins.
- [ ] Print text "White King is under Check" if black checked him. 
- [ ] Print text "Black King is under Check" if white checked him.

**Comment by tuura01** [comment]
#77
